# Default values for blunderlist-comment.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: eu.gcr.io/blunderlist/comment-ts
  tag: stable
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 50051

database:
  name: comment
  user: comment
